spool sys_constr.log
set echo on

ALTER TABLE ADDRESS_RIGHTS
ADD CONSTRAINT FK_ADDRESS_USERNAME FOREIGN KEY (USERNAME)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE API_LIST
ADD CONSTRAINT FK_API_LIST_REPORT FOREIGN KEY (REP)
REFERENCES API_REPORTS(ID) ON DELETE CASCADE
/
ALTER TABLE API_OPTIONS
ADD CONSTRAINT FK_API_OPTIONS_API FOREIGN KEY (API)
REFERENCES API_LIST(ID) ON DELETE CASCADE
/
ALTER TABLE API_USAGE
ADD CONSTRAINT FK_API_USAGE_API FOREIGN KEY (API)
REFERENCES API_LIST(ID) ON DELETE CASCADE
/
ALTER TABLE API_USAGE
ADD CONSTRAINT FK_API_USAGE_REP FOREIGN KEY (REP)
REFERENCES API_REPORTS(ID)
/
ALTER TABLE BELONG_GROUPS_EQUAL
ADD CONSTRAINT FK_BELONG_GROUPS_BELONG_ID FOREIGN KEY (BELONG_ID)
REFERENCES BELONG_GROUPS(ID) ON DELETE CASCADE
/
ALTER TABLE BELONG_GROUPS_EQUAL
ADD CONSTRAINT FK_BELONG_GROUPS_EQUAL_ID FOREIGN KEY (EQUAL_ID)
REFERENCES BELONG_GROUPS(ID) ON DELETE CASCADE
/
ALTER TABLE CALENDAR_VALUE
ADD CONSTRAINT FK_CALENDAR_VALUE_NAME FOREIGN KEY (CALENDAR_NAME)
REFERENCES CALENDARS(NAME) ON DELETE CASCADE
/
ALTER TABLE CHECK_METHOD_RIGHTS
ADD CONSTRAINT FK_CMR_CHECK_METHOD_ID FOREIGN KEY (CHECK_METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE CHECK_METHOD_RIGHTS
ADD CONSTRAINT FK_CMR_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE CHECK_METHOD_RIGHTS
ADD CONSTRAINT FK_CMR_SUBJ_ID FOREIGN KEY (SUBJ_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE CLASSES
ADD CONSTRAINT FK_CLASSES_CRITERIA_ID FOREIGN KEY (CRITERIA_ID)
REFERENCES CRITERIA(ID)
/
ALTER TABLE CLASSES
ADD CONSTRAINT FK_CLASSES_ENTITY_ID FOREIGN KEY (ENTITY_ID)
REFERENCES ENTITIES(ID)
/
ALTER TABLE CLASSES
ADD CONSTRAINT FK_CLASSES_INIT_METHOD_ID FOREIGN KEY (INIT_METHOD_ID)
REFERENCES METHODS(ID)
/
ALTER TABLE CLASSES
ADD CONSTRAINT FK_CLASSES_INIT_STATE_ID FOREIGN KEY (ID,INIT_STATE_ID)
REFERENCES STATES(CLASS_ID,ID)
/
ALTER TABLE CLASSES
ADD CONSTRAINT FK_CLASSES_PARENT_ID FOREIGN KEY (PARENT_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CLASSES
ADD CONSTRAINT FK_CLASSES_TARGET_CLASS_ID FOREIGN KEY (TARGET_CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CLASSES
ADD CONSTRAINT FK_CLASSES_TRIGGER_ID FOREIGN KEY (TRIGGER_ID)
REFERENCES METHODS(ID)
/
ALTER TABLE CLASS_ATTRIBUTES
ADD CONSTRAINT FK_CLS_ATTRS_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CLASS_ATTRIBUTES
ADD CONSTRAINT FK_CLS_ATTR_SELF_CLASSS_ID FOREIGN KEY (SELF_CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CLASS_INDEXES
ADD CONSTRAINT FK_CLASS_INDEXES_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE CLASS_IND_COLUMNS
ADD CONSTRAINT FK_CLASS_IND_COLUMNS_INAME FOREIGN KEY (INDEX_NAME)
REFERENCES CLASS_INDEXES(NAME) ON DELETE CASCADE
/
ALTER TABLE CLASS_PARTITIONS
ADD CONSTRAINT FK_CLASS_PARTITIONS_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CLASS_REC_FIELDS
ADD CONSTRAINT FK_CLS_REC_FIELDS_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE CLASS_RELATIONS
ADD CONSTRAINT FK_CLS_REL_CHILD_ID FOREIGN KEY (CHILD_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CLASS_RELATIONS
ADD CONSTRAINT FK_CLS_REL_PARENT_ID FOREIGN KEY (PARENT_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CLASS_RIGHTS
ADD CONSTRAINT FK_CLASS_RIGHTS_SUBJ_ID FOREIGN KEY (SUBJ_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE CLASS_RIGHTS
ADD CONSTRAINT FK_CR_OBJ_ID FOREIGN KEY (OBJ_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE CLASS_RULES
ADD CONSTRAINT FK_CR_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE CLASS_RULES
ADD CONSTRAINT FK_CR_SUBJ_ID FOREIGN KEY (SUBJ_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE CLASS_TABLES
ADD CONSTRAINT FK_CLASS_TABLES_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CLASS_TAB_COLUMNS
ADD CONSTRAINT FK_CLS_TAB_COLUMNS_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CONTROLS
ADD CONSTRAINT CTL2CLASS FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CONTROLS
ADD CONSTRAINT CTL2CTL_DEPEND FOREIGN KEY (DEPEND)
REFERENCES CONTROLS(ID)
/
ALTER TABLE CONTROLS
ADD CONSTRAINT CTL2CTL_PARENT FOREIGN KEY (PARENT)
REFERENCES CONTROLS(ID)
/
ALTER TABLE CONTROLS
ADD CONSTRAINT CTL2METH FOREIGN KEY (METH_ID)
REFERENCES METHODS(ID)
/
ALTER TABLE CONTROLS
ADD CONSTRAINT FK_CONTROLS_CRIT_CLASS_ID FOREIGN KEY (CRIT_CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE SET NULL
/
ALTER TABLE CONTROLS
ADD CONSTRAINT FK_CONTROLS_CRIT_ID FOREIGN KEY (CRIT_ID)
REFERENCES CRITERIA(ID) ON DELETE SET NULL
/
ALTER TABLE CRITERIA
ADD CONSTRAINT FK_CRITERIA_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE CRITERIA
ADD CONSTRAINT FK_CRITERIA_EXT_ID FOREIGN KEY (EXT_ID)
REFERENCES CRITERIA(ID)
/
ALTER TABLE CRITERIA
ADD CONSTRAINT FK_CRITERIA_SRC_ID FOREIGN KEY (SRC_ID)
REFERENCES CRITERIA(ID)
/
ALTER TABLE CRITERIA_COLUMNS
ADD CONSTRAINT FK_CRIT_COLUMNS_CRITERIA_ID FOREIGN KEY (CRITERIA_ID)
REFERENCES CRITERIA(ID) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_COLUMNS
ADD CONSTRAINT FK_CRIT_COLUMNS_R_CLASS_ID FOREIGN KEY (REF_CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE SET NULL
/
ALTER TABLE CRITERIA_COLUMNS
ADD CONSTRAINT FK_CRIT_COLUMNS_R_CRIT_ID FOREIGN KEY (REF_CRIT_ID)
REFERENCES CRITERIA(ID)
/
ALTER TABLE CRITERIA_COLUMNS
ADD CONSTRAINT FK_CRIT_COLUMNS_T_C_ID FOREIGN KEY (TARGET_CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_COMPLEX
ADD CONSTRAINT FK_CRIT_COMPLEX_CRITERIA_ID FOREIGN KEY (CRITERIA_ID)
REFERENCES CRITERIA(ID) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_COMPLEX
ADD CONSTRAINT FK_CRIT_COMPLEX_JOIN_ID FOREIGN KEY (JOIN_ID)
REFERENCES CRITERIA(ID)
/
ALTER TABLE CRITERIA_COMPLEX_COLUMNS
ADD CONSTRAINT FK_CRIT_CC_CRITERIA_ID FOREIGN KEY (CRITERIA_ID)
REFERENCES CRITERIA(ID) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_METHODS
ADD CONSTRAINT FK_CRITERIA_METHODS_CRIT_ID FOREIGN KEY (CRITERION_ID)
REFERENCES CRITERIA(ID) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_METHODS
ADD CONSTRAINT FK_CRITERIA_METHODS_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_PRINTS
ADD CONSTRAINT FK_CRITERIA_PRINTS_CRITERIA_ID FOREIGN KEY (CRITERIA_ID)
REFERENCES CRITERIA(ID) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_PRINT_COLUMNS
ADD CONSTRAINT FK_CR_PR_COLS_CR_ID_NAME FOREIGN KEY (CRITERIA_ID,PRINT_NAME)
REFERENCES CRITERIA_PRINTS(CRITERIA_ID,NAME) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_RIGHTS
ADD CONSTRAINT FK_CRITERIA_RIGHTS_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_RIGHTS
ADD CONSTRAINT FK_CRITERIA_RIGHTS_OBJ_ID FOREIGN KEY (OBJ_ID)
REFERENCES CRITERIA(ID) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_RIGHTS
ADD CONSTRAINT FK_CRITERIA_RIGHTS_SUBJ_ID FOREIGN KEY (SUBJ_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE CRITERIA_TRIES
ADD CONSTRAINT FK_CRIT_TRIES_CRITERIA_ID FOREIGN KEY (CRITERIA_ID)
REFERENCES CRITERIA(ID) ON DELETE CASCADE
/
ALTER TABLE CURSORS
ADD CONSTRAINT FK_CURSORS_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE FAVORITES
ADD CONSTRAINT FK_FAVORITES_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE FAVORITES
ADD CONSTRAINT FK_FAVORITES_CRITERION_ID FOREIGN KEY (CRITERION_ID)
REFERENCES CRITERIA(ID) ON DELETE CASCADE
/
ALTER TABLE FAVORITES
ADD CONSTRAINT FK_FAVORITES_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE FAVORITES
ADD CONSTRAINT FK_FAVORITES_PARENT_ID FOREIGN KEY (PARENT_ID)
REFERENCES FAVORITES(ID) ON DELETE CASCADE
/
ALTER TABLE FAVORITES
ADD CONSTRAINT FK_FAVORITES_USERNAME FOREIGN KEY (USERNAME)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE FVR_FILTERS
ADD CONSTRAINT FK_FVR_FILTERS_FVR_ID FOREIGN KEY (FVR_ID)
REFERENCES FAVORITES(ID) ON DELETE CASCADE
/
ALTER TABLE HOST2PLP
ADD CONSTRAINT FK_HOST2PLP_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE MACRO_VALUES
ADD CONSTRAINT FK_MACRO_VALUES_DRIVER_ID FOREIGN KEY (DRIVER_ID)
REFERENCES PRINTER_TYPES(ID) ON DELETE CASCADE
/
ALTER TABLE MACRO_VALUES
ADD CONSTRAINT FK_MACRO_VALUES_MACRO_ID FOREIGN KEY (MACRO_ID)
REFERENCES PRINTER_MACROS(ID) ON DELETE CASCADE
/
ALTER TABLE METHODS
ADD CONSTRAINT FK_METHODS_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE METHODS
ADD CONSTRAINT FK_METHODS_EXT_ID FOREIGN KEY (EXT_ID)
REFERENCES METHODS(ID)
/
ALTER TABLE METHODS
ADD CONSTRAINT FK_METHODS_FORM_ID FOREIGN KEY (FORM_ID)
REFERENCES METHODS(ID)
/
ALTER TABLE METHODS
ADD CONSTRAINT FK_METHODS_RESULT_CLASS_ID FOREIGN KEY (RESULT_CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE METHODS
ADD CONSTRAINT FK_METHODS_SRC_ID FOREIGN KEY (SRC_ID)
REFERENCES METHODS(ID)
/
ALTER TABLE METHOD_GROUPS
ADD CONSTRAINT FK_METHOD_GROUPS_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE METHOD_GROUPS
ADD CONSTRAINT FK_METHOD_GROUPS_PARENT_ID FOREIGN KEY (PARENT_ID)
REFERENCES METHOD_GROUPS(ID) ON DELETE CASCADE
/
ALTER TABLE METHOD_GROUPS
ADD CONSTRAINT FK_METH_GROUPS_USERNAME FOREIGN KEY (USERNAME)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE METHOD_GROUP_MEMBERS
ADD CONSTRAINT FK_METH_GRP_MEMB_GROUP_ID FOREIGN KEY (GROUP_ID)
REFERENCES METHOD_GROUPS(ID) ON DELETE CASCADE
/
ALTER TABLE METHOD_GROUP_MEMBERS
ADD CONSTRAINT FK_METH_GRP_MEMB_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE METHOD_PARAMETERS
ADD CONSTRAINT FK_METHOD_PARAMETERS_CRIT_ID FOREIGN KEY (CRIT_ID)
REFERENCES CRITERIA(ID) ON DELETE SET NULL
/
ALTER TABLE METHOD_PARAMETERS
ADD CONSTRAINT FK_METHOD_PARAMS_CRIT_CLASS_ID FOREIGN KEY (CRIT_CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE SET NULL
/
ALTER TABLE METHOD_PARAMETERS
ADD CONSTRAINT FK_MP_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE METHOD_PARAMETERS
ADD CONSTRAINT FK_MP_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID)
/
ALTER TABLE METHOD_RIGHTS
ADD CONSTRAINT FK_METHOD_RIGHTS_SUBJ_ID FOREIGN KEY (SUBJ_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE METHOD_RIGHTS
ADD CONSTRAINT FK_MR_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE METHOD_RIGHTS
ADD CONSTRAINT FK_MR_OBJ_ID FOREIGN KEY (OBJ_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE METHOD_VARIABLES
ADD CONSTRAINT FK_METHOD_VARIABLES_CRIT_ID FOREIGN KEY (CRIT_ID)
REFERENCES CRITERIA(ID) ON DELETE SET NULL
/
ALTER TABLE METHOD_VARIABLES
ADD CONSTRAINT FK_METHOD_VARS_CRIT_CLASS_ID FOREIGN KEY (CRIT_CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE SET NULL
/
ALTER TABLE METHOD_VARIABLES
ADD CONSTRAINT FK_METH_VAR_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE METHOD_VARIABLES
ADD CONSTRAINT FK_METH_VAR_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID)
/
ALTER TABLE NUM_ATTRIBUTES
ADD CONSTRAINT FK_NUM_ATTRIBUTES FOREIGN KEY (NUM_ID)
REFERENCES NUMERATORS(ID)
/
ALTER TABLE OBJECTS_OPTIONS
ADD CONSTRAINT FK_OBJECTS_OPTIONS_OPTION FOREIGN KEY (OPTION_ID)
REFERENCES SYSTEM_OPTIONS(ID) ON DELETE CASCADE
/
ALTER TABLE OBJECT_RULES
ADD CONSTRAINT FK_OBJECT_RULES_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE OBJECT_RULES
ADD CONSTRAINT FK_OBJECT_RULES_SUBJ_ID FOREIGN KEY (SUBJ_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE OBJ_STATIC
ADD CONSTRAINT FK_OBJ_STATIC_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/

var s varchar2(30);
exec :s := inst_info.downer1
column tmpcol new_value tmpowner noprint
select :s tmpcol from dual;
select nvl(owner,:s) tmpcol from project where type='TABLE' and name='ORSA_JOBS';

ALTER TABLE &&tmpowner..ORSA_JOBS_OUT
ADD CONSTRAINT FK_ORSA_JOBS_OUT_JOB_POS FOREIGN KEY (JOB,POS)
REFERENCES &&tmpowner..ORSA_JOBS(JOB,POS) ON DELETE CASCADE
/
ALTER TABLE &&tmpowner..ORSA_JOBS_PAR
ADD CONSTRAINT FK_ORSA_JOBS_PAR_JOB_POS FOREIGN KEY (JOB,POS)
REFERENCES &&tmpowner..ORSA_JOBS(JOB,POS) ON DELETE CASCADE
/
ALTER TABLE &&tmpowner..ORSA_PAR_LOB
ADD CONSTRAINT FK_ORSA_PAR_LOB FOREIGN KEY (JOB,POS)
REFERENCES &&tmpowner..ORSA_JOBS(JOB,POS) ON DELETE CASCADE
/
ALTER TABLE PROCEDURE_RIGHTS
ADD CONSTRAINT FK_PROC_RGHT_OBJ_ID FOREIGN KEY (OBJ_ID)
REFERENCES PROCEDURES(NAME) ON DELETE CASCADE
/
ALTER TABLE PROCEDURE_RIGHTS
ADD CONSTRAINT FK_PROC_RGHT_SUBJ_ID FOREIGN KEY (SUBJ_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE PROJECT_ENTRY_ATTRIBUTES
ADD CONSTRAINT FK_PROC_ATTR_PROJECT_ID FOREIGN KEY (PROJECT_ID)
REFERENCES PROJECTS(ID) ON DELETE CASCADE
/
ALTER TABLE PROJECT_ENTRY_ATTRIBUTES
ADD CONSTRAINT FK_PROJECT_ENTRY_ATTR_PID_EID FOREIGN KEY (PROJECT_ID,ENTRY_ID)
REFERENCES PROJECT_ENTRIES(PROJECT_ID,ID) ON DELETE CASCADE
/
ALTER TABLE REPORT_FORMULA
ADD CONSTRAINT FK_REPORT_FORMULA_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID)
/
ALTER TABLE REPORT_OBJECTS
ADD CONSTRAINT FK_REPORT_OBJECTS_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE REPORT_PARAM_RELATIONS
ADD CONSTRAINT FK_RPT_PARAM_REL_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE SECURITY_DOMAINS
ADD CONSTRAINT FK_SECURITY_DOMAINS_PAR_ID FOREIGN KEY (PARENT_ID)
REFERENCES SECURITY_DOMAINS(ID) ON DELETE CASCADE DEFERRABLE
/
ALTER TABLE SECURITY_DOMAINS
ADD CONSTRAINT FK_SECURITY_DOMAINS_RES_GRP FOREIGN KEY (RESOURCE_GROUP)
REFERENCES USERS(USERNAME)
/
ALTER TABLE SECURITY_DOMAINS
ADD CONSTRAINT FK_SECURITY_DOMAINS_REV_GRP FOREIGN KEY (REVISOR_GROUP)
REFERENCES USERS(USERNAME)
/
ALTER TABLE SEC_DOMAIN_ENTRIES
ADD CONSTRAINT FK_SEC_DOMAIN_ENTRIES_DOM_ID FOREIGN KEY (DOMAIN_ID)
REFERENCES SECURITY_DOMAINS(ID) ON DELETE CASCADE DEFERRABLE
/
ALTER TABLE SEC_DOMAIN_ENTRIES
ADD CONSTRAINT FK_SEC_DOMAIN_ENTRIES_USR_ID FOREIGN KEY (USER_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE SEC_DOMAIN_EQUALS
ADD CONSTRAINT FK_SEC_DOMAIN_EQUALS_CHLD_ID FOREIGN KEY (CHILD_ID)
REFERENCES SECURITY_DOMAINS(ID) ON DELETE CASCADE DEFERRABLE
/
ALTER TABLE SEC_DOMAIN_EQUALS
ADD CONSTRAINT FK_SEC_DOMAIN_EQUALS_PAR_ID FOREIGN KEY (PARENT_ID)
REFERENCES SECURITY_DOMAINS(ID) ON DELETE CASCADE DEFERRABLE
/
ALTER TABLE SEQUENCES
ADD CONSTRAINT FK_SEQUENCES FOREIGN KEY (NUM_ID)
REFERENCES NUMERATORS(ID)
/
ALTER TABLE STATES
ADD CONSTRAINT FK_STATES_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID)
/
ALTER TABLE SUBJ_EQUAL
ADD CONSTRAINT FK_SUBJ_EQUAL_EQUAL_ID FOREIGN KEY (EQUAL_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE SUBJ_EQUAL
ADD CONSTRAINT FK_SUBJ_EQUAL_SUBJ_ID FOREIGN KEY (SUBJ_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE SYSTEM_OPTIONS
ADD CONSTRAINT FK_SYSTEM_OPTIONS_PAR_ID FOREIGN KEY (PARENT_ID)
REFERENCES SYSTEM_OPTIONS(ID)
/
ALTER TABLE TRANSITIONS
ADD CONSTRAINT FK_TRANS_CLASS_FIN_STATE_ID FOREIGN KEY (CLASS_ID,FINAL_STATE_ID)
REFERENCES STATES(CLASS_ID,ID)
/
ALTER TABLE TRANSITIONS
ADD CONSTRAINT FK_TRANS_CLASS_INI_STATE_ID FOREIGN KEY (CLASS_ID,INITIAL_STATE_ID)
REFERENCES STATES(CLASS_ID,ID)
/
ALTER TABLE TRANSITION_METHODS
ADD CONSTRAINT FK_TRN_METHS_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE TRANSITION_METHODS
ADD CONSTRAINT FK_TRN_METHS_EXT_ID FOREIGN KEY (EXT_ID)
REFERENCES METHODS(ID) ON DELETE SET NULL
/
ALTER TABLE TRANSITION_METHODS
ADD CONSTRAINT FK_TRN_METHS_METHOD_ID FOREIGN KEY (METHOD_ID)
REFERENCES METHODS(ID) ON DELETE CASCADE
/
ALTER TABLE TRANSITION_RIGHTS
ADD CONSTRAINT FK_TRANSITION_RIGHTS_SUBJ_ID FOREIGN KEY (SUBJ_ID)
REFERENCES USERS(USERNAME) ON DELETE CASCADE
/
ALTER TABLE TRANSITION_RIGHTS
ADD CONSTRAINT FK_TR_CLASS_ID FOREIGN KEY (CLASS_ID)
REFERENCES CLASSES(ID) ON DELETE CASCADE
/
ALTER TABLE TRANSITION_RIGHTS
ADD CONSTRAINT FK_TR_OBJ_ID FOREIGN KEY (OBJ_ID)
REFERENCES TRANSITIONS(ID) ON DELETE CASCADE
/

set echo off
spool off

