SET VERIFY OFF
connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool /u/app/oracle/admin/work/scripts/CreateDB.log append
startup nomount pfile="/u/app/oracle/admin/work/scripts/init.ora";
CREATE DATABASE "work"
MAXINSTANCES 8
MAXLOGHISTORY 1
MAXLOGFILES 16
MAXLOGMEMBERS 3
MAXDATAFILES 100
DATAFILE '/db1/oradata/work/system01.dbf' SIZE 700M REUSE AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
SYSAUX DATAFILE '/db1/oradata/work/sysaux01.dbf' SIZE 550M REUSE AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED
SMALLFILE DEFAULT TEMPORARY TABLESPACE TEMP TEMPFILE '/db1/oradata/work/temp01.dbf' SIZE 20M REUSE AUTOEXTEND ON NEXT  640K MAXSIZE UNLIMITED
SMALLFILE UNDO TABLESPACE "UNDOTBS1" DATAFILE  '/db1/oradata/work/undotbs01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT  5120K MAXSIZE UNLIMITED
CHARACTER SET CL8ISO8859P5 
NATIONAL CHARACTER SET AL16UTF16
LOGFILE GROUP 1 ('/db1/oradata/work/redo01.log') SIZE 50M,
GROUP 2 ('/db1/oradata/work/redo02.log') SIZE 50M,
GROUP 3 ('/db1/oradata/work/redo03.log') SIZE 50M
USER SYS IDENTIFIED BY "&&sysPassword" USER SYSTEM IDENTIFIED BY "&&systemPassword";
spool off
