alter table SECURITY_DOMAINS add RESOURCE_GROUP varchar2(30);

alter table SECURITY_JOBS modify USER_CREATED varchar2(100);

drop index IDX_SECURITY_DOMAINS_REV_GRP;

create unique index IDX_SECURITY_DOMAINS_REV_GRP
  on SECURITY_DOMAINS ( REVISOR_GROUP )
  TABLESPACE &&TSPACEI;

create unique index IDX_SECURITY_DOMAINS_RES_GRP
  on SECURITY_DOMAINS ( RESOURCE_GROUP )
  TABLESPACE &&TSPACEI;

alter table SECURITY_DOMAINS add constraint FK_SECURITY_DOMAINS_RES_GRP
  foreign key (RESOURCE_GROUP) references USERS(USERNAME);
