SET VERIFY OFF
connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool /u/app/oracle/admin/work/scripts/CreateDBFiles.log append
CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/db1/oradata/work/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO;
ALTER DATABASE DEFAULT TABLESPACE "USERS";
CREATE SMALLFILE TABLESPACE "T_USR" LOGGING  DATAFILE  '/db1/oradata/work/t_usr01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL uniform size 128K SEGMENT SPACE MANAGEMENT  AUTO;
CREATE SMALLFILE TABLESPACE "I_USR" LOGGING  DATAFILE  '/db1/oradata/work/i_usr01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL uniform size 128K SEGMENT SPACE MANAGEMENT  AUTO;
CREATE SMALLFILE TABLESPACE "T_DICT" LOGGING  DATAFILE  '/db1/oradata/work/t_dict01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL uniform size 128K SEGMENT SPACE MANAGEMENT  AUTO;
CREATE SMALLFILE TABLESPACE "I_DICT" LOGGING  DATAFILE  '/db1/oradata/work/i_dict01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL uniform size 128K SEGMENT SPACE MANAGEMENT  AUTO;
CREATE SMALLFILE TABLESPACE "T_AUD" LOGGING  DATAFILE  '/db1/oradata/work/t_aud01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL uniform size 128K SEGMENT SPACE MANAGEMENT  AUTO;
CREATE SMALLFILE TABLESPACE "I_AUD" LOGGING  DATAFILE  '/db1/oradata/work/i_aud01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL uniform size 128K SEGMENT SPACE MANAGEMENT  AUTO;

spool off
