VER2
REM Список элементов
REM IBS@X0D198_TEST2
REM Версия ТЯ: 7.3.7.0
REM Версия Администратора проектов: 6.93.0.76

TYPE RECALL_MTD_CFG   'Настройки перевызова операций
ATTR RECALL_MTD_CFG METACLASS_ID
ATTR RECALL_MTD_CFG METHOD_SHORTNAME
ATTR RECALL_MTD_CFG MODE_PROG
CRIT RECALL_MTD_CFG VW_CRIT_RECALL_MTD_CFG
CRIT RECALL_MTD_CFG VW_CRIT_RECALL_MTD_CFG_PROG
METH RECALL_MTD_CFG DELETE_AUTO
METH RECALL_MTD_CFG EDIT_AUTO
METH RECALL_MTD_CFG NEW_AUTO
