DEFINE DIARY='0'
DEFINE DIARY_PARAM='10'
DEFINE VALUES_HISTORY='11'
DEFINE OBJECT_STATE_HISTORY='12'

DEFINE DIARY1='1';
DEFINE DIARY2='2';
DEFINE DIARY3='3';
DEFINE DIARY4='4';
DEFINE DIARY5='5';
DEFINE DIARY6='6';
DEFINE DIARY7='7';
DEFINE VALSH='-1';
DEFINE OSH='-2';
DEFINE OCH='-3';
DEFINE DP='-4';
DEFINE EDH='-5';

DEFINE SUFFIX_DIARY1='DIARY1';
DEFINE SUFFIX_DIARY2='DIARY2';
DEFINE SUFFIX_DIARY3='DIARY3';
DEFINE SUFFIX_DIARY4='DIARY4';
DEFINE SUFFIX_DIARY5='DIARY5';
DEFINE SUFFIX_DIARY6='DIARY6';
DEFINE SUFFIX_DIARY7='DIARY7';
DEFINE SUFFIX_VALSH='VALSH';
DEFINE SUFFIX_OSH='OSH';
DEFINE SUFFIX_OCH='OCH';
DEFINE SUFFIX_DP='DP';
DEFINE SUFFIX_EDH='EDH';

DEFINE STEP_DIARY1='M';
DEFINE STEP_DIARY2='M';
DEFINE STEP_DIARY3='Q';
DEFINE STEP_DIARY4='Q';
DEFINE STEP_DIARY5='Q';
DEFINE STEP_DIARY6='M';
DEFINE STEP_DIARY7='M';
DEFINE STEP_VALSH='M';
DEFINE STEP_OSH='M';
DEFINE STEP_OCH='M';
DEFINE STEP_DP='M';
DEFINE STEP_EDH='Q';
DEFINE D_TIME_TZ=''

set termout off
column yyy new_value D_TIME_TZ noprint
select ' with time zone' yyy from dual
 where :db_version>8 and &&own_ver>6.4 and upper(substr('&&D_USE_TZ',1,1)) in ('Y','1');
set termout on

DEFINE COLUMNS_DIARY1='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, AUDSID NUMBER, USER_ID VARCHAR2 (70), TOPIC CHAR (1), CODE VARCHAR2 (30), TEXT VARCHAR2 (4000)'
DEFINE COLUMNS_DIARY2='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, AUDSID NUMBER, USER_ID VARCHAR2 (70), TOPIC CHAR (1), CODE VARCHAR2 (30), TEXT VARCHAR2 (4000)'
DEFINE COLUMNS_DIARY3='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, AUDSID NUMBER, USER_ID VARCHAR2 (70), TOPIC CHAR (1), CODE VARCHAR2 (30), TEXT VARCHAR2 (4000)'
DEFINE COLUMNS_DIARY4='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, AUDSID NUMBER, USER_ID VARCHAR2 (70), TOPIC CHAR (1), CODE VARCHAR2 (30), TEXT VARCHAR2 (4000)'
DEFINE COLUMNS_DIARY5='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, AUDSID NUMBER, USER_ID VARCHAR2 (70), TOPIC CHAR (1), CODE VARCHAR2 (30), TEXT VARCHAR2 (4000)'
DEFINE COLUMNS_DIARY6='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, AUDSID NUMBER, USER_ID VARCHAR2 (70), TOPIC CHAR (1), CODE VARCHAR2 (30), TEXT VARCHAR2 (4000)'
DEFINE COLUMNS_DIARY7='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, AUDSID NUMBER, USER_ID VARCHAR2 (70), TOPIC CHAR (1), CODE VARCHAR2 (30), TEXT VARCHAR2 (4000)'
DEFINE COLUMNS_VALSH='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, OBJ_ID VARCHAR2(128), CLASS_ID VARCHAR2(16), AUDSID NUMBER, USER_ID VARCHAR2 (70), QUAL VARCHAR2 (700), BASE_ID VARCHAR2 (16), VALUE VARCHAR2 (4000)'
DEFINE COLUMNS_OSH='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, OBJ_ID VARCHAR2(128), CLASS_ID VARCHAR2(16), STATE_ID VARCHAR2 (16), AUDSID NUMBER, USER_ID VARCHAR2 (70)'
DEFINE COLUMNS_OCH='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, OBJ_ID VARCHAR2(128), CLASS_ID VARCHAR2(16), COLLECTION_ID NUMBER, OBJ_PARENT VARCHAR2 (2000), AUDSID NUMBER, USER_ID VARCHAR2 (70)'
DEFINE COLUMNS_DP='DIARY_ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, QUAL VARCHAR2 (700), BASE_ID VARCHAR2 (16), TEXT VARCHAR2 (4000)'
DEFINE COLUMNS_EDH='ID NUMBER, TIME &&D_TIMESTAMP&&D_TIME_TZ, OBJ_ID VARCHAR2(128), CLASS_ID VARCHAR2(16), AUDSID NUMBER, USER_ID VARCHAR2 (70), TYPE_ID VARCHAR2 (16), CODE VARCHAR2 (70), TEXT VARCHAR2 (4000)'

