@settings\defaults

define DIARY_TYPE=&&DIARY1
define DIARY_SUFFIX=&&SUFFIX_DIARY1
define DIARY_STEP=&&STEP_DIARY1
define DIARY_COLUMNS='&&COLUMNS_DIARY1'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&DIARY2
define DIARY_SUFFIX=&&SUFFIX_DIARY2
define DIARY_STEP=&&STEP_DIARY2
define DIARY_COLUMNS='&&COLUMNS_DIARY2'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&DIARY3
define DIARY_SUFFIX=&&SUFFIX_DIARY3
define DIARY_STEP=&&STEP_DIARY3
define DIARY_COLUMNS='&&COLUMNS_DIARY3'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&DIARY4
define DIARY_SUFFIX=&&SUFFIX_DIARY4
define DIARY_STEP=&&STEP_DIARY4
define DIARY_COLUMNS='&&COLUMNS_DIARY4'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&DIARY5
define DIARY_SUFFIX=&&SUFFIX_DIARY5
define DIARY_STEP=&&STEP_DIARY5
define DIARY_COLUMNS='&&COLUMNS_DIARY5'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&DIARY6
define DIARY_SUFFIX=&&SUFFIX_DIARY6
define DIARY_STEP=&&STEP_DIARY6
define DIARY_COLUMNS='&&COLUMNS_DIARY6'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&DIARY7
define DIARY_SUFFIX=&&SUFFIX_DIARY7
define DIARY_STEP=&&STEP_DIARY7
define DIARY_COLUMNS='&&COLUMNS_DIARY7'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&VALSH
define DIARY_SUFFIX=&&SUFFIX_VALSH
define DIARY_STEP=&&STEP_VALSH
define DIARY_COLUMNS='&&COLUMNS_VALSH'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&OSH
define DIARY_SUFFIX=&&SUFFIX_OSH
define DIARY_STEP=&&STEP_OSH
define DIARY_COLUMNS='&&COLUMNS_OSH'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&OCH
define DIARY_SUFFIX=&&SUFFIX_OCH
define DIARY_STEP=&&STEP_OCH
define DIARY_COLUMNS='&&COLUMNS_OCH'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&DP
define DIARY_SUFFIX=&&SUFFIX_DP
define DIARY_STEP=&&STEP_DP
define DIARY_COLUMNS='&&COLUMNS_DP'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

define DIARY_TYPE=&&EDH
define DIARY_SUFFIX=&&SUFFIX_EDH
define DIARY_STEP=&&STEP_EDH
define DIARY_COLUMNS='&&COLUMNS_EDH'
define DIARY_TBS=&&TUSER
define DIARY_IDX_TBS=&&TSPACEI
@settings\set_tbl

