VER2
REM Список элементов
REM IBS@57_DEV
REM Версия ТЯ: 6.6.1.1
REM Версия Администратора проектов: 6.79.0.15

METH SYS_DIARYS GROUP_RIGHTS
METH SYS_DIARYS USER_RIGHTS
METH USER GROUP_RIGHTS
METH USER USER_RIGHTS
