VER2
REM Список элементов
REM IBS@57_DEV
REM Версия ТЯ: 6.4.0.3
REM Версия Администратора проектов: 6.73.0.11

CRIT USERS VW_CRIT_EQUAL_SUBJ
CRIT USERS VW_CRIT_GROUPS
CRIT USERS VW_CRIT_SUBJ_EQUAL
CRIT USERS VW_CRIT_USERS
