VER2
REM Список элементов
REM IBS@X0D198UI
REM Версия ТЯ: 7.3.3.0
REM Версия Администратора проектов: 6.93.0.54

TYPE FILE$LOAD   'Экспорт-импорт файлов
ATTR FILE$LOAD DST_DELETE
ATTR FILE$LOAD DST_MASK
ATTR FILE$LOAD DST_NAME
ATTR FILE$LOAD DST_PATH
ATTR FILE$LOAD DST_TYPE
ATTR FILE$LOAD SRC_DELETE
ATTR FILE$LOAD SRC_MASK
ATTR FILE$LOAD SRC_NAME
ATTR FILE$LOAD SRC_PATH
ATTR FILE$LOAD SRC_TYPE
METH FILE$LOAD FILE_CHECK
TYPE FILE$MASK   'Файловая маска
TYPE FILE$PATH   'Полное имя файла
