VER2
REM Список элементов
REM IBS@X0D198_TEST2
REM Версия ТЯ: 7.4.1.4
REM Версия Администратора проектов: 6.93.0.96

TYPE JOB_MACHINE   'Платформа 2MCA: Список серверов заданий
ATTR JOB_MACHINE HOST
ATTR JOB_MACHINE LAST_TIME
ATTR JOB_MACHINE START_TIME
CRIT JOB_MACHINE VW_CRIT_LIST_JOB_MACHINE
IDX JOB_MACHINE IDX_Z#JOB_MACHINE_HOST
METH JOB_MACHINE CHK_JOB_MACHINE
METH JOB_MACHINE JOB_RT_MANAGER
