VER2
REM Список элементов
REM IBS@CORE_PATCH
REM Версия ТЯ: 7.3.2.1
REM Версия Администратора проектов: 6.93.0.115

METH RUNTIME CALENDAR
METH RUNTIME EDOC
METH RUNTIME HTTP_MGR
METH RUNTIME RESOURCE_MGR
